spring.application.name=reports_service
server.port=${SERVER_PORT}
server.servlet.context-path=/${SERVICE_BASE_URL}

# Base de datos
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#cors y configuraciones del backend
app.frontendHost=${FRONTEND_ORIGIN}
backend.host=${BACKEND_ORIGIN}

spring.mvc.contentnegotiation.default-content-type=application/json
spring.mvc.converters.preferred-json-mapper=jackson

#JWT
jwt.secret=${JWT_SECRET}
jwt.refresh-secret=${JWT_REFRESH_SECRET}
jwt.expires-in=20h
jwt.refresh-expires-in=20h

# Emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Archivos
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

#microservices
app.microservice.url=${MICROSERVICE_URL}
