spring.application.name=reports_service
server.port=${SERVER_PORT}
server.servlet.context-path=/${SERVICE_BASE_URL}

# Base de datos
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#cors y configuraciones del backend
app.frontendHost=${FRONTEND_ORIGIN}
backend.host=${BACKEND_ORIGIN}

spring.mvc.contentnegotiation.default-content-type=application/json
spring.mvc.converters.preferred-json-mapper=jackson

#JWT
jwt.secret=${JWT_SECRET}
jwt.refresh-secret=${JWT_REFRESH_SECRET}
jwt.expires-in=20h
jwt.refresh-expires-in=20h

# Emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Archivos
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Microservices databases (Postgres FDW)
# auth
fdw.external[0].name=${DB_AUTH_NAME:auth}
fdw.external[0].host=${DB_AUTH_HOST:auth-db}
fdw.external[0].port=${DB_AUTH_PORT:5432}
fdw.external[0].dbname=${DB_AUTH_DBNAME:congress_auth_db}
fdw.external[0].username=${DB_AUTH_USER:postgres}
fdw.external[0].password=${DB_AUTH_PASSWORD:password}

# congress
fdw.external[1].name=${DB_CONGRESS_NAME:congress}
fdw.external[1].host=${DB_CONGRESS_HOST:congress-db}
fdw.external[1].port=${DB_CONGRESS_PORT:5432}
fdw.external[1].dbname=${DB_CONGRESS_DBNAME:congress_congress_db}
fdw.external[1].username=${DB_CONGRESS_USER:postgres}
fdw.external[1].password=${DB_CONGRESS_PASSWORD:password}

# payments
fdw.external[2].name=${DB_PAYMENTS_NAME:payments}
fdw.external[2].host=${DB_PAYMENTS_HOST:payments-db}
fdw.external[2].port=${DB_PAYMENTS_PORT:5432}
fdw.external[2].dbname=${DB_PAYMENTS_DBNAME:congress_payments_db}
fdw.external[2].username=${DB_PAYMENTS_USER:postgres}
fdw.external[2].password=${DB_PAYMENTS_PASSWORD:password}

# registration
fdw.external[3].name=${DB_REGISTRATION_NAME:registration}
fdw.external[3].host=${DB_REGISTRATION_HOST:registration-db}
fdw.external[3].port=${DB_REGISTRATION_PORT:5432}
fdw.external[3].dbname=${DB_REGISTRATION_DBNAME:congress_registration_db}
fdw.external[3].username=${DB_REGISTRATION_USER:postgres}
fdw.external[3].password=${DB_REGISTRATION_PASSWORD:password}

# activity
fdw.external[4].name=${DB_ACTIVITY_NAME:activity}
fdw.external[4].host=${DB_ACTIVITY_HOST:activity-db}
fdw.external[4].port=${DB_ACTIVITY_PORT:5432}
fdw.external[4].dbname=${DB_ACTIVITY_DBNAME:congress_activity_db}
fdw.external[4].username=${DB_ACTIVITY_USER:postgres}
fdw.external[4].password=${DB_ACTIVITY_PASSWORD:password}

# attendance
fdw.external[5].name=${DB_ATTENDANCE_NAME:attendance}
fdw.external[5].host=${DB_ATTENDANCE_HOST:attendance-db}
fdw.external[5].port=${DB_ATTENDANCE_PORT:5432}
fdw.external[5].dbname=${DB_ATTENDANCE_DBNAME:congress_attendance_db}
fdw.external[5].username=${DB_ATTENDANCE_USER:postgres}
fdw.external[5].password=${DB_ATTENDANCE_PASSWORD:password}

# works
fdw.external[6].name=${DB_WORKS_NAME:works}
fdw.external[6].host=${DB_WORKS_HOST:works-db}
fdw.external[6].port=${DB_WORKS_PORT:5432}
fdw.external[6].dbname=${DB_WORKS_DBNAME:congress_works_db}
fdw.external[6].username=${DB_WORKS_USER:postgres}
fdw.external[6].password=${DB_WORKS_PASSWORD:password}