# Logs
logging.level.root=INFO
logging.level.org.springframework=WARN

# Actuator restringido
management.endpoints.web.exposure.include=health

# Swagger deshabilitado
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false