# Logs
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG

# Endpoints de actuator
management.endpoints.web.exposure.include=*

#SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json