name: deploy_to_dev.yml
on:
  push:
    branches:
      - dev

env:
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE_OWNER: ${{ vars.IMAGE_OWNER }}
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}
  NEW_IMAGE_TAG: "dev-${{ github.sha }}"
  ENV_TAG_NAME: ${{ vars.ENV_TAG_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR
        run: |
          chmod +x mvnw
          ./mvnw clean package

      - name: Prepare artifact
        run: cp target/*.jar service.jar

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/$SERVICE_NAME:$NEW_IMAGE_TAG .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_OWNER/$SERVICE_NAME:$NEW_IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: GITHUB_TOKEN,REGISTRY,IMAGE_OWNER,SERVICE_NAME,NEW_IMAGE_TAG,ENV_TAG_NAME
          script: |
            set -e
            printf "%s" "$GITHUB_TOKEN" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
            cd ~/cnb_congress
            echo "Deploying version: $NEW_IMAGE_TAG"
            sed -i "s/^${ENV_TAG_NAME}=.*/${ENV_TAG_NAME}=${NEW_IMAGE_TAG}/" .env
            docker compose pull $SERVICE_NAME
            docker compose up -d $SERVICE_NAME
            docker logout $REGISTRY
            echo "Deploy complete"